food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.IndexClassView.as_view(),name='index'),
    path('item/', views.item, name='item'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('add/',views.CreateItem.as_view(), name='create_item'),
    path('edit/<int:pk>', views.update_item, name='update_item'),
    path('delete/<int:pk>', views.delete_item, name='delete_item')
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.contrib.auth import views as authentication_views

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', views.register, name='register'),
    path('profile/', views.profilepage, name='profile'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

app_name = 'users'
urlpatterns = [


]

food/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default='https://www.jennycancook.com/wp-content/uploads/2014/08/comingsoon-480x300.jpg')

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("food:index")

users/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='pig.png',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.views.generic import ListView, DetailView, CreateView

from .form import ItemForm
from .models import Item

# Create your views here.

def item(request):
    item_list = Item.objects.all()
    context = {'item_list': item_list}
    # template = loader.get_template('food/index.html')
    # return HttpResponse(template.render(context,request))
    return render(request,'food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def detail(request, pk):
    item = Item.objects.get(pk=pk)
    context = {'item':item}
    return render(request,'food/detail.html',context)

class DetailView(DetailView):
    model = Item
    template_name ='food/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item_form.html', {'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    def form_valid(self, form):
        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item_form.html', {'form':form, 'item':item})

def delete_item(request, pk):
    item = Item.objects.get(id=pk)
    if request.method == "POST":
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


# Create your views here.
def register(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'{username} create sucessfully')
            return redirect('food:index')
        else:
            form = UserCreationForm()
    return render(request, 'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

def test(request):
    pass

food/templates/food/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food App</a>
    <div class="navbar">
        <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
        <a class="nav-item nav-link" href="#">Delete Item</a>
        <a class="nav-item nav-link" href="#">Edit Item</a>
        {% if user.is_authenticated %}
        <a href={% url 'logout' %}>Logout</a>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        {% endif %}
            <a  class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>

    </div>
        </nav>
    {% block body %}
    {% endblock %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tag }}">
    {{ message }}
</div>
{% endfor %}
{% endif %}

</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
 <div class="container">
        <div class="row">
        <div class="col-md-6">
            <img class="card" height="300px" src="{{ object.item_image }}"/>
        </div>
        <div class="col-md-6">
           <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>{{ object.item_price }}</h3>
        </div>
    </div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% block body %}
 <div class="container-fluid">
    {% for item in item_list %}
        <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card" height="150px" src="{{ item.item_image }}"/>
        </div>
        <div class="col-md-4">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_desc }}</h5>
            <h6>{{ item.item_price }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Detail</a>
        </div>
    </div>
{% endfor %}
 </div>

{% endblock %}

food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}
 <form method="post">
    {% csrf_token %}
     <h2>Are you sure to delete {{ item.item_name }}?</h2>
    <button type="submit">Confirm</button>
 </form>
{% endblock %}

food/templates/food/item_form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">Add item</div>
                </div>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.name }}
                        <br>
                        {{ field }}
                    </div>
                    {% endfor %}
                <button class="btn-info" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">Login</div>
                </div>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.name }}
                        {{ field }}
                    </div>
                    {% endfor %}
                <button class="btn-info" type="submit">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
<h1>You have been logout.</h1>
<div>
<a href="{% url 'login' %}">Login</a>
</div>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width="100px" height="100px" src="{{ user.profile.image.url}}">
<h2>{{ user.profile.image.url}}</h2>

users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">Register</div>
                </div>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.name }}
                        <br>
                        {{ field }}
                    </div>
                    {% endfor %}
                <button class="btn-info" type="submit">Register</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}